version: "3"
services:
  app:
    container_name: nodejs
    restart: always
    image: node:latest
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    working_dir: /app
    entrypoint: /bin/sh -c "npm run server:build && npm run build && npm run serve"
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./db:/data/db
  nginx:
    depends_on:
      - mongodb
      - app
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./build:/static
      - ./keys:/etc/ssl
    ports:
      - 80:80
      - 443:443
